GET https://api.binance.com/api/v3/exchangeInfo
Accept: application/json

###

GET https://api.binance.com/api/v3/trades?symbol=BTCUSDT&limit=100
Accept: application/json

###

GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m
Accept: application/json
